name: Automated Deployment to AWS EC2

on:
  push:
    branches:
      - main  # Robot akan bekerja setiap kali kamu push ke branch main

jobs:
  deploy-backend:
    name: Deploy Backend to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi Perintah di Server Backend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_BACKEND }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tani-vision
            git pull origin main
            sudo docker compose up -d --build backend

  deploy-frontend:
    name: Deploy Frontend to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi Perintah di Server Frontend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_FRONTEND }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tani-vision
            git pull origin main
            sudo docker compose up -d --build frontend